language: node_js
node_js:
- '6'
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_2d00c239cd79_key -iv $encrypted_2d00c239cd79_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 103.42.214.153\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_script:
- npm run build
after_success:
- tar --exclude node_modules --exclude src --exclude score.tar.gz -zcf score.tar.gz *   # 打包并压缩代码
- scp score.tar.gz server@121.41.50.22:~/tmp/score.tar.gz  # 复制到生产服务器上
- ssh server@121.41.50.22 'rm -rf ~/score/*'
- ssh server@121.41.50.22 'cd ~/score && tar -zxf ~/tmp/score.tar.gz -C . && yarn --prod && pm2 startOrRestart score.config.js'
