language: node_js
node_js:
- '6'
branches:
  only:
    - master
before_install:
- openssl aes-256-cbc -K $encrypted_2d00c239cd79_key -iv $encrypted_2d00c239cd79_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 103.42.214.153\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_script:
- npm run build
after_success:
- tar --exclude node_modules --exclude src -jcf score.tar.bz2 *    # 打包并压缩代码
- scp score.tar.bz2 root@103.42.214.153:~/tmp/score.tar.bz2  # 复制到生产服务器上
#- ssh root@103.42.214.153 'pm2 delete all && rm -rf `ls /project/score/|awk "{if($0 != 'node_modules/') print $0}"`'
- ssh root@103.42.214.153 'pm2 delete all && rm -rf /project/score/*'
- ssh root@103.42.214.153 'cd ~/project/score && tar -jxf ~/tmp/score.tar.bz2 -C .'   # 解压
- ssh root@103.42.214.153 'cd ~/project/score && yarn --prod && pm2 start score.config.js'   # 运行
